name: Java CI with Maven

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: "Test with ${{ matrix.os }}"
    strategy:
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04, ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - uses: actions/setup-java@v4
        with:
          java-version: '8.0.345'
          distribution: temurin
      - name: Print Docker Config
        run: cat ~/.docker/config.json
      - name: Print Docker Daemon
        run: cat /etc/docker/daemon.json
      - name: Build with Maven
        run: mvn -V -B verify
